<?php
require_once __DIR__.'/config.php';
function db(){ static $pdo; if($pdo)return $pdo; $pdo=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); return $pdo; }
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function redirect($url){header('Location: '.$url);exit;}
function logged(){return !empty($_SESSION['user']);}
function admin(){return !empty($_SESSION['admin']);}
function flash($msg,$type='ok'){$_SESSION['flash']=[$msg,$type];}
function get_flash(){ $x=$_SESSION['flash']??null; unset($_SESSION['flash']); return $x; }
function header_html($title='Serenova Hotel'){ $f=get_flash(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | Serenova Hotel</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#f7f4ee;color:#202824}.navbar{background:#13221d}.brand{color:#e2bd72!important;font-weight:900}.hero{background:linear-gradient(90deg,#101c18d9,#101c1866),url('https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1800&q=85') center/cover;min-height:62vh;color:white;display:flex;align-items:center}.gold{color:#b17e37}.btn-gold{background:#c99d52;color:#fff;border:0}.card{border:1px solid #e3dccf}.room-img{height:230px;object-fit:cover}.footer{background:#111916;color:#ccd2cf}.stat{background:white;border-left:4px solid #c99d52}.sidebar a{color:#dfe7e2;text-decoration:none;display:block;padding:10px}.sidebar a:hover{background:#263a32}.table{background:#fff}</style></head><body><nav class="navbar navbar-expand-lg navbar-dark"><div class="container"><a class="navbar-brand brand" href="index.php">SERENOVA HOTEL</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div id="nav" class="collapse navbar-collapse"><div class="navbar-nav ms-auto"><a class="nav-link" href="index.php">Home</a><a class="nav-link" href="rooms.php">Rooms</a><?php if(logged()): ?><a class="nav-link" href="my-bookings.php">My Bookings</a><?php endif; ?><?php if(admin()): ?><a class="nav-link" href="admin/index.php">Admin</a><?php endif; ?><?php if(logged()||admin()): ?><a class="nav-link" href="logout.php">Logout</a><?php else: ?><a class="nav-link" href="login.php">Login</a><a class="nav-link" href="register.php">Register</a><?php endif; ?></div></div></div></nav><?php if($f): ?><div class="container mt-3"><div class="alert alert-<?=e($f[1])?>"><?=e($f[0])?></div></div><?php endif; ?><?php }
function footer_html(){?><footer class="footer mt-5 py-4"><div class="container d-flex justify-content-between"><div><b>SERENOVA HOTEL</b><br>Dodoma, Tanzania</div><div>© <?=date('Y')?> Serenova Hotel</div></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html><?php }