<?php
$PRACTICALS = [
 ['id'=>'bio-osmosis','subject'=>'Biology','level'=>'O-Level','title'=>'Osmosis using plant tissue','topic'=>'Transport in plants','tags'=>['osmosis','potato','water potential'],'aim'=>'To investigate the effect of solution concentration on water movement in plant tissue.','formula'=>'Percentage change in mass = ((final mass - initial mass) / initial mass) × 100','graph'=>'Plot percentage change in mass against solution concentration.','safety'=>'Use clean apparatus, handle blades carefully and clean spills immediately.'],
 ['id'=>'bio-food-tests','subject'=>'Biology','level'=>'O-Level','title'=>'Food tests','topic'=>'Nutrition','tags'=>['food tests','starch','protein','reducing sugar'],'aim'=>'To test food samples for major nutrients using appropriate reagents.','formula'=>'Record colour change and state the positive test result.','graph'=>'A graph is optional when quantitative measurements are collected.','safety'=>'Wear eye protection and follow reagent handling instructions.'],
 ['id'=>'bio-photosynthesis','subject'=>'Biology','level'=>'O-Level','title'=>'Effect of light on photosynthesis','topic'=>'Photosynthesis','tags'=>['photosynthesis','light','oxygen'],'aim'=>'To investigate how light conditions affect the rate of photosynthesis.','formula'=>'Rate = quantity of product formed / time','graph'=>'Plot rate of photosynthesis against the independent variable.','safety'=>'Avoid direct exposure to strong lamps and allow apparatus to cool.'],
 ['id'=>'bio-enzymes','subject'=>'Biology','level'=>'A-Level','title'=>'Effect of temperature on enzyme activity','topic'=>'Enzymes','tags'=>['enzymes','temperature','rate'],'aim'=>'To investigate the effect of temperature on enzyme activity.','formula'=>'Rate = 1 / reaction time (for a fixed endpoint)','graph'=>'Plot enzyme activity/rate against temperature.','safety'=>'Use a water bath carefully and avoid burns.'],
 ['id'=>'chem-titration','subject'=>'Chemistry','level'=>'O-Level','title'=>'Acid-base titration','topic'=>'Acids, bases and salts','tags'=>['titration','indicator','concentration'],'aim'=>'To determine an unknown concentration using a standard solution and an indicator.','formula'=>'C₁V₁/n₁ = C₂V₂/n₂ for a balanced reaction','graph'=>'For ordinary titration, use titre tables and concordant results; advanced investigations may plot titration curves.','safety'=>'Wear goggles, handle acids/alkalis carefully and rinse spills immediately.'],
 ['id'=>'chem-rate','subject'=>'Chemistry','level'=>'A-Level','title'=>'Effect of concentration on reaction rate','topic'=>'Chemical kinetics','tags'=>['rate','concentration','kinetics'],'aim'=>'To investigate how concentration affects reaction rate.','formula'=>'Rate = change in measured quantity / time','graph'=>'Plot rate against concentration or a suitable transformed variable.','safety'=>'Use small quantities and appropriate protective equipment.'],
 ['id'=>'chem-electrolysis','subject'=>'Chemistry','level'=>'O-Level','title'=>'Electrolysis of an electrolyte','topic'=>'Electrochemistry','tags'=>['electrolysis','electrodes','ions'],'aim'=>'To observe products formed during electrolysis and relate them to electrode reactions.','formula'=>'Q = It; moles of electrons = Q/F','graph'=>'Where measurements vary with current or time, plot the dependent variable against the independent variable.','safety'=>'Keep electrical connections dry and handle chemicals according to their hazards.'],
 ['id'=>'phys-hooke','subject'=>'Physics','level'=>'O-Level','title'=>"Hooke's law experiment",'topic'=>'Mechanics','tags'=>['spring','force','extension','elasticity'],'aim'=>"To investigate the relationship between applied force and extension of a spring.",'formula'=>'F = kx','graph'=>'Plot force against extension; gradient gives the spring constant k in the linear region.','safety'=>'Do not overload the spring and keep feet clear of falling masses.'],
 ['id'=>'phys-pendulum','subject'=>'Physics','level'=>'O-Level','title'=>'Simple pendulum','topic'=>'Oscillations','tags'=>['pendulum','period','gravity'],'aim'=>'To determine the relationship between pendulum length and period and estimate gravitational acceleration.','formula'=>'T = 2π√(L/g); T² = (4π²/g)L','graph'=>'Plot T² against L; gradient = 4π²/g.','safety'=>'Secure the support and keep the oscillation small.'],
 ['id'=>'phys-lens','subject'=>'Physics','level'=>'O-Level','title'=>'Focal length of a converging lens','topic'=>'Optics','tags'=>['lens','focal length','image'],'aim'=>'To determine the focal length of a converging lens using object and image measurements.','formula'=>'1/f = 1/u + 1/v','graph'=>'A suitable transformed plot can be used to determine focal length from gradient/intercept.','safety'=>'Never look directly at the Sun through a lens.'],
 ['id'=>'phys-resistance','subject'=>'Physics','level'=>'A-Level','title'=>'Resistance of a conductor','topic'=>'Electricity','tags'=>['resistance','current','voltage','Ohm'],'aim'=>'To investigate the relationship between potential difference and current.','formula'=>'V = IR','graph'=>'Plot V against I; gradient gives resistance for an ohmic conductor.','safety'=>'Use low voltages, avoid overheating and switch off before changing connections.'],
];
